# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Vickening
email: chrisinajar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The website for Kayla Wilbanks and Chris Vickery's wedding, The Vickening.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thevickening.com" # the base hostname & protocol for your site
twitter_username: chrisinajar
github_username:  chrisinajar

exclude: [vendor]

# Build settings
markdown: kramdown

wedding_time: 1504382400000

# set up authors and /team/ pages
collections:
  authors:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
